### ISSUE TITLE
Question on ESlint and prettier

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/authentication-service#10]
-I see we're using eslint & prettier. @hharnisc do you think that should be incorporated into CI? Or should we suggest that linting/auto-code formatting is the responsibility of the individual?

This may be a good conversation to have on how we could approach this across projects at Buffer. I'm very open minded on this one, so would love to hear what you think!

**Comment by hharnisc** [comment]
I've gone back and forth so much on linting in general. There are a couple of things that seem to matter the most here:

1. does linting speed things up or get in the way
2. does linting teach best practices (and standardize) or spread bad habits 

I think linter/prettier actually does help with 1 and helps with 2 so long as the individual uses a linter/prettier plugin in their editor. Prettier's defaults (with a couple small tweaks) are actually pretty good (at least good enough) and get us within range of 2.

That being said if we do linting/prettier we should run prettier and let it fail if it does not match the commit in diff. This at least alerts the team that _something_ is not conforming to the project's standards.

The last part here is something we'll need to think about, what rules do we actually use. We've got a couple options:

1. Somehow share the rules for all JS projects (an NPM package perhaps?)
2. Write some documentation and mark these as the _suggested_ set of rules
3. Every project can do what they want

Personally I think 2 is a good enough option here, but 1 could also be a very good option (needs some research). I do think that if a set of lint rules is defined, it should be considered failing if the format is off.


I'll adjust the tests to fail if the format is off as an action item. We should also discus the above options @djfarrelly

**Comment by djfarrelly** [comment]
Great points @hharnisc. I think linting can help consistency/readability across the team so much so that it's not too utterly specific or a pain for a developer to confirm to all the time. Prettier works similar to say running `go fmt` in golang on file save right?

I'm definitely curious about how we could roll this out across our team and have people add plugins to their editors. I think a combination of options 1 & 2 is great, but allow projects to opt-in when they want. For example it might take quite a bit for Reply to opt in and they may not want to right now. What do you think?
