### ISSUE TITLE
Documenting our choice on bcrypt

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/authentication-service#14]
Hey @hharnisc, I had not recently dove into the world of passwords and just did some reading on sha* vs. bcrypt and from my general reading it feels like crypt is the way to go for more security. It being slower than sha256 is a positive thing. I also read how it stores the salt right in the hash which is convenient too rather than needing another field for this. 

@hharnisc is this what your findings are too? Are there any other reasons that you chose to use this method for hashing passwords over an alternative?

This isn't so much of a questioning the initial approach, but more of being intentional about our choice and documenting it for posterity! 😄

**Comment by hharnisc** [comment]
Hey @djfarrelly! 

You're spot on with your findings :smile: a couple things to add.

The big one is that each tool has been designed for a different purpose:

bcrypt = encryption
sha* = hashing

Encryption algorithms are usually intentionally slow, where hashing algorithms are usually much faster. Both can achieve a similar effect, however hashing requires more work to reach the level of security of *crypt. If you only hash something once without a random string attached someone could use a hashing table to crack a password. The salt being stored in the string is quite nice in *crypt as well.

Another big one is that *crypt is the more common approach to storing passwords. Someone who's already familiar with another authentication service will have less to learn when looking at this one.

**Comment by djfarrelly** [comment]
Thanks for your additions @hharnisc! 💯 on everything here, super clear to me and hope this helps if anyone in the future has a question.
