### ISSUE TITLE
Project file structure

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/authentication-service#15]
@hharnisc what do you think about the pattern of project file structure for RPC services like this:

```
src/
  index.js
  functions/
    createUser.js
    ...
  models/
    Account.js
  lib/
    someUtilModule.js
```

I like the functions, but it might be nice for small or large projects to have a little bit of organization/hierarchy for readability and understanding. I think this might also allow a developer to just go right to `/functions` to see all the functions they can expect to call from `/rpc/*`.

I know this project is quite small, but this could be a good one to think on to set a pattern for future services 😉 

---

Even following this pattern we could create a method in `micro-rpc` to load all functions from a directory... _pseudo-code_:

```js
// passing the directory and it could dynamically require them all
app.post('/rpc', (req, res, next) =>
  rpc(path.join(__dirname, './functions'))(req, res).catch(err => next(err))
)
// or a little different
const { rpc, loadFunctions } = require('micro-rpc')
const functions = loadFunctions(path.join(__dirname, './functions'))
app.post('/rpc', rpc(functions))
```

This part above is just fun to think about where we could take the micro-rpc library to make it DRYer

**Comment by hharnisc** [comment]
:+1: I'll reorganize the repository:

```
src/
  rpc/ <- index.js exports named functions
  modules/ <- index.js exports named models
  index.js <- entry point
```

Need to think through importing the all the rpc endpoints dynamically -- there's some tradeoffs there

**Comment by hharnisc** [comment]
There's probably something there with the dynamic loading of imports, but that might be better to be baked into micro-rpc (you've actually kind of done that in the pseudo code). I'm thinking we revisit that one later :smile:
