### ISSUE TITLE
API authentication – use of headers, something else?

### ISSUE THREAD

**Issue by twanlass** [bufferapp/authentication-service#4]
Just wondering how we'll secure these endpoints. Maybe use header tokens to auth requests from other systems?

From Humber: 
> headers are great because they are in the body (and encrypted over when using HTTPS) and not logged like query params by intermediate systems

**Comment by hharnisc** [comment]
Intentionally left this out so we've got some wiggle room to figure this out. Currently thinking we'll lock down the API using [Istio](https://istio.io/). Istio is a layer 7 load balancer -- which lets us keep the API authentication separate from the business logic. We can use headers or even just a simple check on the service name that is making the request (whitelisting the services that can access) would be enough.
