### ISSUE TITLE
api/verify used in combination with existing Reply authorize service?

### ISSUE THREAD

**Issue by twanlass** [bufferapp/authentication-service#7]
Just curious if you're thinking we'd use `api/verify` to verify a user then we'd issue a JWT from our existing Reply auth service? In the future, the buffer auth service would handle this though (maybe cookies)?

**Comment by hharnisc** [comment]
Great question! The way I've been thinking about the authorization service is that it is the source of truth for verifying a user's credentials. For the MVP I think that Reply would still issue the JWT to the client just like it does today, and would do so after checking with the authorization service that the user is who they say they are.

Check out this network diagram, it show's the basic flow for `api/verify` (after an account has been created)

https://github.com/bufferapp/authentication-service/blob/master/images/LoginFromLinkedProduct.png

If you're curious here's the network diagram for creating a new account:

https://github.com/bufferapp/authentication-service/blob/master/images/CreateAccountLinkProduct.png

Post MVP in a future iteration we'll likely want to use the `login.buffer.com` service to verify users and issue the session. It would still need the help of Reply (via an endpoint that does not exist yet) to return reply specific session data and any cookies to pass along to the client. This would be a great one to do a whiteboard session on at the retreat. Here's the network diagram for that flow:

https://github.com/bufferapp/authentication-service/blob/master/images/LoginFromModerator.png
